
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - federation.kubefed.fulliautomatix.site
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - federation.kubefed.fulliautomatix.site
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - types.kubefed.io
  resources:
  - federatedconfigmaps
  - federateddeployments
  - federatedservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
